### ISSUE TITLE
Array and Map object

### ISSUE THREAD

**Issue by dpauli** [BlackBonjour/stdlib#11]
We need an Array and Map object to handle avoid using native *arrays*.

*Array* should only have values with automatic incremented int key.

*Map* maps only strings => attributes.

See https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html
and https://docs.oracle.com/javase/7/docs/api/java/util/Map.html

**Comment by BlackBonjour** [comment]
Done with https://github.com/BlackBonjour/stdlib/commit/722e99cf49b145146d88926315e64edf17f152a3.

**Comment by BlackBonjour** [comment]
Yeah... I'm stupid af. I forgot to add that array stuff. Will be added in version 0.5.
