### ISSUE TITLE
[Assert] Add ::notEmpty method or extend ::empty

### ISSUE THREAD

**Issue by BlackBonjour** [BlackBonjour/stdlib#21]
Assert::empty acts like PHP isset: It will return true if all values are empty.

We need a new method or extend existing ones, that returns true if even only one value is empty.

**Comment by dpauli** [comment]
A new method makes more sense ;)

**Comment by BlackBonjour** [comment]
Done with https://github.com/BlackBonjour/stdlib/commit/a1a15ac9a3fb8346473f6e8ab6385a6199664520.
