### ISSUE TITLE
null check assertions only work with uppercase

### ISSUE THREAD

**Issue by dpauli** [BlackBonjour/stdlib#36]
The following function call does not work:

```
$var = null;
Assert::typeOf('null', $var);
```
and call following Exception:

```
TypeError : Expected value to be of type null, NULL given!
```

The problem is, that `gettype(null)` is `NULL` and not `null`.

**Comment by BlackBonjour** [comment]
That is a correct behaviour as the assertion is build on top of `gettype`. What I could do is to add some constants for all available types which than could be used instead.

**Comment by BlackBonjour** [comment]
Feature comes with the release of 3.0.
